package com.example.bookstore.mybatis.dao;

import com.example.bookstore.mybatis.model.Customorder;
import java.util.List;

public interface CustomorderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.CUSTOMORDER
     *
     * @mbg.generated Sat Apr 12 13:53:24 EEST 2025
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.CUSTOMORDER
     *
     * @mbg.generated Sat Apr 12 13:53:24 EEST 2025
     */
    int insert(Customorder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.CUSTOMORDER
     *
     * @mbg.generated Sat Apr 12 13:53:24 EEST 2025
     */
    Customorder selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.CUSTOMORDER
     *
     * @mbg.generated Sat Apr 12 13:53:24 EEST 2025
     */
    List<Customorder> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.CUSTOMORDER
     *
     * @mbg.generated Sat Apr 12 13:53:24 EEST 2025
     */
    int updateByPrimaryKey(Customorder record);
}