package com.example.bookstore.mybatis.model;

import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.util.ArrayList;
import java.util.List;

@Getter
@Setter
@NoArgsConstructor
public class Book {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.BOOK.ID
     *
     * @mbg.generated Sun Apr 13 15:23:54 EEST 2025
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.BOOK.AUTHOR
     *
     * @mbg.generated Sun Apr 13 15:23:54 EEST 2025
     */
    private String author;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.BOOK.PAGECOUNT
     *
     * @mbg.generated Sun Apr 13 15:23:54 EEST 2025
     */
    private Integer pagecount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.BOOK.PRICE
     *
     * @mbg.generated Sun Apr 13 15:23:54 EEST 2025
     */
    private Double price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.BOOK.TITLE
     *
     * @mbg.generated Sun Apr 13 15:23:54 EEST 2025
     */
    private String title;

    private List<Customorder> customorders = new ArrayList<>();

    public Book(String author, Integer pagecount, Double price, String title) {
        this.author = author;
        this.pagecount = pagecount;
        this.price = price;
        this.title = title;
    }
}