package com.example.bookstore.mybatis.model;

public class Book {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.BOOK.ID
     *
     * @mbg.generated Sun Apr 13 15:23:54 EEST 2025
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.BOOK.AUTHOR
     *
     * @mbg.generated Sun Apr 13 15:23:54 EEST 2025
     */
    private String author;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.BOOK.PAGECOUNT
     *
     * @mbg.generated Sun Apr 13 15:23:54 EEST 2025
     */
    private Integer pagecount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.BOOK.PRICE
     *
     * @mbg.generated Sun Apr 13 15:23:54 EEST 2025
     */
    private Double price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.BOOK.TITLE
     *
     * @mbg.generated Sun Apr 13 15:23:54 EEST 2025
     */
    private String title;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.BOOK.ID
     *
     * @return the value of PUBLIC.BOOK.ID
     *
     * @mbg.generated Sun Apr 13 15:23:54 EEST 2025
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.BOOK.ID
     *
     * @param id the value for PUBLIC.BOOK.ID
     *
     * @mbg.generated Sun Apr 13 15:23:54 EEST 2025
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.BOOK.AUTHOR
     *
     * @return the value of PUBLIC.BOOK.AUTHOR
     *
     * @mbg.generated Sun Apr 13 15:23:54 EEST 2025
     */
    public String getAuthor() {
        return author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.BOOK.AUTHOR
     *
     * @param author the value for PUBLIC.BOOK.AUTHOR
     *
     * @mbg.generated Sun Apr 13 15:23:54 EEST 2025
     */
    public void setAuthor(String author) {
        this.author = author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.BOOK.PAGECOUNT
     *
     * @return the value of PUBLIC.BOOK.PAGECOUNT
     *
     * @mbg.generated Sun Apr 13 15:23:54 EEST 2025
     */
    public Integer getPagecount() {
        return pagecount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.BOOK.PAGECOUNT
     *
     * @param pagecount the value for PUBLIC.BOOK.PAGECOUNT
     *
     * @mbg.generated Sun Apr 13 15:23:54 EEST 2025
     */
    public void setPagecount(Integer pagecount) {
        this.pagecount = pagecount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.BOOK.PRICE
     *
     * @return the value of PUBLIC.BOOK.PRICE
     *
     * @mbg.generated Sun Apr 13 15:23:54 EEST 2025
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.BOOK.PRICE
     *
     * @param price the value for PUBLIC.BOOK.PRICE
     *
     * @mbg.generated Sun Apr 13 15:23:54 EEST 2025
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.BOOK.TITLE
     *
     * @return the value of PUBLIC.BOOK.TITLE
     *
     * @mbg.generated Sun Apr 13 15:23:54 EEST 2025
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.BOOK.TITLE
     *
     * @param title the value for PUBLIC.BOOK.TITLE
     *
     * @mbg.generated Sun Apr 13 15:23:54 EEST 2025
     */
    public void setTitle(String title) {
        this.title = title;
    }
}