package com.example.bookstore.mybatis.model;

public class Customorder {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.CUSTOMORDER.ID
     *
     * @mbg.generated Sun Apr 13 15:23:54 EEST 2025
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.CUSTOMORDER.PAYMENTMETHOD
     *
     * @mbg.generated Sun Apr 13 15:23:54 EEST 2025
     */
    private String paymentmethod;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.CUSTOMORDER.FKCUSTOMERID
     *
     * @mbg.generated Sun Apr 13 15:23:54 EEST 2025
     */
    private Integer fkcustomerid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.CUSTOMORDER.ID
     *
     * @return the value of PUBLIC.CUSTOMORDER.ID
     *
     * @mbg.generated Sun Apr 13 15:23:54 EEST 2025
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.CUSTOMORDER.ID
     *
     * @param id the value for PUBLIC.CUSTOMORDER.ID
     *
     * @mbg.generated Sun Apr 13 15:23:54 EEST 2025
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.CUSTOMORDER.PAYMENTMETHOD
     *
     * @return the value of PUBLIC.CUSTOMORDER.PAYMENTMETHOD
     *
     * @mbg.generated Sun Apr 13 15:23:54 EEST 2025
     */
    public String getPaymentmethod() {
        return paymentmethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.CUSTOMORDER.PAYMENTMETHOD
     *
     * @param paymentmethod the value for PUBLIC.CUSTOMORDER.PAYMENTMETHOD
     *
     * @mbg.generated Sun Apr 13 15:23:54 EEST 2025
     */
    public void setPaymentmethod(String paymentmethod) {
        this.paymentmethod = paymentmethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.CUSTOMORDER.FKCUSTOMERID
     *
     * @return the value of PUBLIC.CUSTOMORDER.FKCUSTOMERID
     *
     * @mbg.generated Sun Apr 13 15:23:54 EEST 2025
     */
    public Integer getFkcustomerid() {
        return fkcustomerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.CUSTOMORDER.FKCUSTOMERID
     *
     * @param fkcustomerid the value for PUBLIC.CUSTOMORDER.FKCUSTOMERID
     *
     * @mbg.generated Sun Apr 13 15:23:54 EEST 2025
     */
    public void setFkcustomerid(Integer fkcustomerid) {
        this.fkcustomerid = fkcustomerid;
    }
}