package com.example.bookstore.mybatis.model;

public class Customer {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.CUSTOMER.ID
     *
     * @mbg.generated Sat Apr 12 13:53:24 EEST 2025
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.CUSTOMER.FIRSTNAME
     *
     * @mbg.generated Sat Apr 12 13:53:24 EEST 2025
     */
    private String firstname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.CUSTOMER.LASTNAME
     *
     * @mbg.generated Sat Apr 12 13:53:24 EEST 2025
     */
    private String lastname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.CUSTOMER.MIDDLENAME
     *
     * @mbg.generated Sat Apr 12 13:53:24 EEST 2025
     */
    private String middlename;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.CUSTOMER.ID
     *
     * @return the value of PUBLIC.CUSTOMER.ID
     *
     * @mbg.generated Sat Apr 12 13:53:24 EEST 2025
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.CUSTOMER.ID
     *
     * @param id the value for PUBLIC.CUSTOMER.ID
     *
     * @mbg.generated Sat Apr 12 13:53:24 EEST 2025
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.CUSTOMER.FIRSTNAME
     *
     * @return the value of PUBLIC.CUSTOMER.FIRSTNAME
     *
     * @mbg.generated Sat Apr 12 13:53:24 EEST 2025
     */
    public String getFirstname() {
        return firstname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.CUSTOMER.FIRSTNAME
     *
     * @param firstname the value for PUBLIC.CUSTOMER.FIRSTNAME
     *
     * @mbg.generated Sat Apr 12 13:53:24 EEST 2025
     */
    public void setFirstname(String firstname) {
        this.firstname = firstname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.CUSTOMER.LASTNAME
     *
     * @return the value of PUBLIC.CUSTOMER.LASTNAME
     *
     * @mbg.generated Sat Apr 12 13:53:24 EEST 2025
     */
    public String getLastname() {
        return lastname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.CUSTOMER.LASTNAME
     *
     * @param lastname the value for PUBLIC.CUSTOMER.LASTNAME
     *
     * @mbg.generated Sat Apr 12 13:53:24 EEST 2025
     */
    public void setLastname(String lastname) {
        this.lastname = lastname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.CUSTOMER.MIDDLENAME
     *
     * @return the value of PUBLIC.CUSTOMER.MIDDLENAME
     *
     * @mbg.generated Sat Apr 12 13:53:24 EEST 2025
     */
    public String getMiddlename() {
        return middlename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.CUSTOMER.MIDDLENAME
     *
     * @param middlename the value for PUBLIC.CUSTOMER.MIDDLENAME
     *
     * @mbg.generated Sat Apr 12 13:53:24 EEST 2025
     */
    public void setMiddlename(String middlename) {
        this.middlename = middlename;
    }
}