package com.example.bookstore.mybatis.model;

import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.util.ArrayList;
import java.util.List;

@NoArgsConstructor
@Getter
@Setter
public class Customer {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.CUSTOMER.ID
     *
     * @mbg.generated Sun Apr 13 15:23:54 EEST 2025
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.CUSTOMER.FIRSTNAME
     *
     * @mbg.generated Sun Apr 13 15:23:54 EEST 2025
     */
    private String firstname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.CUSTOMER.LASTNAME
     *
     * @mbg.generated Sun Apr 13 15:23:54 EEST 2025
     */
    private String lastname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.CUSTOMER.MIDDLENAME
     *
     * @mbg.generated Sun Apr 13 15:23:54 EEST 2025
     */
    private String middlename;

    private List<Customorder> customorders = new ArrayList<>();

    public Customer(String firstname, String lastname, String middlename) {
        this.firstname = firstname;
        this.lastname = lastname;
        this.middlename = middlename;
    }

    public Customer(String firstname, String middlename, String lastname, List<Customorder> customorders) {
        this(firstname, middlename, lastname);
        this.customorders = customorders;
    }

}